### ISSUE TITLE
Made for an older version of Minecraft

### ISSUE THREAD

**Issue by Hydra9268** [killjoy1221/HD-Font-Generator#1]
Fantastic tool!

Are there any plans to update this to 1.9.4 and 1.10?

**Comment by mattmess1221** [comment]
All that would be needed is to change the pack_format in the pack.json. So no. It's simple enough that you can do it yourself 

The pack will still load ingame anyway.

**Comment by Hydra9268** [comment]
Simple enough. Thanks!

**Comment by mattmess1221** [comment]
ecc235400b289e362831a1f030ca8cec26344d39
8ca6eafbfcd28b836aa2c63ab8742305664b1a94

**Comment by mattmess1221** [comment]
5 years isn't the worst time to close an issue. Is it?
