### ISSUE TITLE
Tahoma bold

### ISSUE THREAD

**Issue by DOUGL4S1** [killjoy1221/HD-Font-Generator#10]
Hi, i'm kind of a newbie to all of this, so idk where to ask and how to do stuff lol

I want to generate the Tahoma Bold font with this program, which is under the Tahoma font. I can create the Tahoma font no issues, but I can't find where/how to create one with it in bold.

Sorry if I missed something or posted this in the wrong place.

**Comment by mattmess1221** [comment]
Only regular font styles are supported.

**Comment by DOUGL4S1** [comment]
alright, thanks!
