### ISSUE TITLE
specific font not showing up

### ISSUE THREAD

**Issue by arceuss** [killjoy1221/HD-Font-Generator#5]
![image](https://user-images.githubusercontent.com/28229451/119558006-1f061580-bd5e-11eb-8808-e6826a867e40.png)
the specific font im trying to use is https://github.com/FMS-Cat/Wt-Position but it isnt anywhere in the program

**Comment by arceuss** [comment]
ok built from source but 
![image](https://user-images.githubusercontent.com/28229451/119558681-f29ec900-bd5e-11eb-8b57-8e93291dcddd.png)

**Comment by mattmess1221** [comment]
If you're building from source, it creates a zip file at `build/distributions/hdfontgen-<version>.zip`. If you extract it, it will include a bat script to launch the application at `hdfontgen-<version>/bin/hdfontgen.bat`.

Yesterday, I included a task that uses jlink and jpackage to bundle a JRE. Use the `jpackage` task to create the bundle. It will be in (depending on OS):

Windows: `build/jpackage/hdfontgen/hdfontgen.exe`
Mac: `build/jpackage/hdfontgen.app`
Linux: `build/jpackage/hdfontgen/bin/hdfontgen`

These packages can be found pre-built at the [releases](https://github.com/killjoy1221/HD-Font-Generator/releases/tag/1.3.0) page
