### ISSUE TITLE
Can't download the latest JAR File.

### ISSUE THREAD

**Issue by Cadmium620** [killjoy1221/HD-Font-Generator#8]
**On that page is only the Sourcecode... Where is the executable JAR?**

**Comment by mattmess1221** [comment]
There is no jar (yet). But building is simple enough. Gradle will even download java for you, assuming you have at least 1 version installed. Just clone the repo and run gradlew build.

    gradlew build

**Comment by mattmess1221** [comment]
I'm playing around with release [1.3.0-rc.1](https://github.com/killjoy1221/HD-Font-Generator/releases/tag/1.3.0-rc.1). Not quite sure why the version is unspecified, but it should still work.
