### ISSUE TITLE
Unicode does not work at x64 or higher

### ISSUE THREAD

**Issue by Cadmium620** [killjoy1221/HD-Font-Generator#9]
It says only "Working...".
I need unicode, because german umlauts and special letters like ä,ö,ü or ß won't be displayed without unicode.

![image](https://user-images.githubusercontent.com/106585614/171824518-20abb6b1-8e66-4f98-ac7e-418b4bfd6b02.png)

**Comment by Cadmium620** [comment]
Version 1.2

**Comment by mattmess1221** [comment]
There are 256 pages to render, so it takes a while. Try using 1.3.0_rc.1
and enabling parallel.
